/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAddUnits: typeof import('./src/components/AdminAddUnits.vue')['default']
    AdminNavigation: typeof import('./src/components/AdminNavigation.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AutoGenerateQuestions: typeof import('./src/components/AutoGenerateQuestions.vue')['default']
    ClozeQuestions: typeof import('./src/components/ClozeQuestions.vue')['default']
    CreateQuestions: typeof import('./src/components/CreateQuestions.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginToQuiz: typeof import('./src/components/LoginToQuiz.vue')['default']
    Practice: typeof import('./src/components/Practice.vue')['default']
    QuestionGlimpse: typeof import('./src/components/QuestionGlimpse.vue')['default']
    QuizQuestion: typeof import('./src/components/QuizQuestion.vue')['default']
    QuizResults: typeof import('./src/components/QuizResults.vue')['default']
    RegisterAccount: typeof import('./src/components/RegisterAccount.vue')['default']
    RegistrarCreateAccounts: typeof import('./src/components/RegistrarCreateAccounts.vue')['default']
    RegistrarNavigation: typeof import('./src/components/RegistrarNavigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentNavigation: typeof import('./src/components/StudentNavigation.vue')['default']
  }
}
