/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/cloze_questions': RouteRecordInfo<'/cloze_questions', '/cloze_questions', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/multiple_questions': RouteRecordInfo<'/multiple_questions', '/multiple_questions', Record<never, never>, Record<never, never>>,
    '/registration': RouteRecordInfo<'/registration', '/registration', Record<never, never>, Record<never, never>>,
    '/student_portal': RouteRecordInfo<'/student_portal', '/student_portal', Record<never, never>, Record<never, never>>,
  }
}
