/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin_add_unit': RouteRecordInfo<'/admin_add_unit', '/admin_add_unit', Record<never, never>, Record<never, never>>,
    '/cloze_questions': RouteRecordInfo<'/cloze_questions', '/cloze_questions', Record<never, never>, Record<never, never>>,
    '/create_cloze_questions': RouteRecordInfo<'/create_cloze_questions', '/create_cloze_questions', Record<never, never>, Record<never, never>>,
    '/create_questions': RouteRecordInfo<'/create_questions', '/create_questions', Record<never, never>, Record<never, never>>,
    '/human_mc_questions': RouteRecordInfo<'/human_mc_questions', '/human_mc_questions', Record<never, never>, Record<never, never>>,
    '/multiple_questions': RouteRecordInfo<'/multiple_questions', '/multiple_questions', Record<never, never>, Record<never, never>>,
    '/registration': RouteRecordInfo<'/registration', '/registration', Record<never, never>, Record<never, never>>,
    '/student_portal': RouteRecordInfo<'/student_portal', '/student_portal', Record<never, never>, Record<never, never>>,
    '/unauthorised': RouteRecordInfo<'/unauthorised', '/unauthorised', Record<never, never>, Record<never, never>>,
  }
}
